language: python
dist: xenial
branches:
  only:
  - master
  - development
python:
  - "3.5"
  - "3.6"
  - "3.7"
env:
  - DJANGO=django111
  - DJANGO=django20
  - DJANGO=django21
  - DJANGO=django22
before_install:
  - sudo apt-get update && sudo apt-get build-dep python-imaging
  - sudo service postgresql restart
install:
  - pip install tox
addons:
  postgresql: "9.6"
  apt:
    packages:
    - postgresql-9.6-postgis-2.4
services:
  - postgresql
before_script:
  - psql template1 -c "create extension hstore;"
  - psql template1 -c "create extension postgis;"
  - psql template1 -c "create extension citext;"
script:
  - TOX_TEST_PASSENV="TRAVIS TRAVIS_JOB_ID TRAVIS_BRANCH" tox -e py${TRAVIS_PYTHON_VERSION//[.]/}-$DJANGO-{postgresql}
  - TOX_TEST_PASSENV="TRAVIS TRAVIS_JOB_ID TRAVIS_BRANCH" tox -e py${TRAVIS_PYTHON_VERSION//[.]/}-$DJANGO-{sqlite}
