sudo: true
language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"
env:
  - DJANGO=django15
  - DJANGO=django16
  - DJANGO=django17
  - DJANGO=django18
  - DJANGO=django19
  - DJANGO=django110
matrix:
  exclude:
    - python: "2.6"
      env: DJANGO=django17
    - python: "2.6"
      env: DJANGO=django18
    - python: "2.6"
      env: DJANGO=django19
    - python: "3.4"
      env: DJANGO=django14
    - python: "3.5"
      env: DJANGO=django14
    - python: "3.5"
      env: DJANGO=django15
    - python: "3.5"
      env: DJANGO=django16
    - python: "3.5"
      env: DJANGO=django17
before_install:
  - sudo apt-get update && sudo apt-get build-dep python-imaging
install:
 - pip install tox
addons:
  postgresql: "9.4"
services:
  - postgresql
before_script:
  - psql -U postgres -c "create extension postgis"
  - psql -c 'create database model_mommy;' -U postgres
  - psql -c 'create database model_mommy_test;' -U postgres
script:
  - TOX_TEST_PASSENV="TRAVIS TRAVIS_JOB_ID TRAVIS_BRANCH" tox -e py${TRAVIS_PYTHON_VERSION//[.]/}-$DJANGO-{postgresql}
  - TOX_TEST_PASSENV="TRAVIS TRAVIS_JOB_ID TRAVIS_BRANCH" tox -e py${TRAVIS_PYTHON_VERSION//[.]/}-$DJANGO-{sqlite}
